import { font } from "@/lib/fonts";
import "./globals.css";

export const metadata = {
  title: "Next app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
